name: teacher
channels:
  - conda-forge
dependencies:
  - streamlit
  - protobuf=4.25.3
  - altair=5.3.0
  - blinker>=1.7.0
  - cachetools=5.3.3
  - click=8.1.7
  - numpy=1.26.4
  - packaging>=24.0
  - pandas=2.2.1
  - pillow=10.3.0
  - protobuf=4.25.3
  - pyarrow=15.0.2
  - requests=2.31.0
  - rich=13.7.1
  - tenacity=8.2.3
  - toml=0.10.2
  - typing-extensions=4.11.0
  - watchdog=4.0.0
  - pathlib
  - numpy
  - typst
  - typst-py=0.10.0
  - xlsxwriter


