name: teacher
channels:
  - conda-forge
dependencies:
  - protobuf=4.25.3
  - altair=3.3.0
  - blinker>1.0.0,<2
  - cachetools>4.0,<6
  - click>7.0,<9
  - numpy>1.19.3,<2
  - packaging>16.8,<25
  - pandas>1.3.0,<3
  - pillow>7.1.0,<11
  - protobuf>3.20,<5
  - pyarrow>7.0
  - requests>2.27,<3
  - rich>10.14.0,<14
  - tenacity>8.1.0,<9
  - toml>0.10.1,<2
  - typing-extensions>4.3.0,<5
  - watchdog>2.1.5
  - pathlib
  - numpy
  - typst
  - streamlit
  - xlsxwriter