# .streamlit/secrets.toml

# This file should not be in the repo, but in this case I don't mind since it is not a secret
# the linked spreadsheet is public and has no sensitive information. Remember, you need to
# configure the same secrets in the streamlit community cloud for this to work.

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/13-iOyDWkuMhYWBbH-4n3LmChTw4NhhWnimGRRIQR-2c/edit?gid=659541200#gid=659541200"


               